## echo server

In [1]:
import socket

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
HOST2 = '192.168.0.103'
PORT2= 65452 
    
# Bind the socket to the port
server_address = (HOST2, PORT2)

print('Starting up on {} port {}'.format(*server_address))
sock.bind(server_address)

# Listen for incoming connections
sock.listen(1)

while True:
    # Wait for a connection
    print('waiting for a connection')
    connection, client_address = sock.accept()
    try:
        print('connection from', client_address)

        # Receive the data in small chunks and retransmit it
        while True:
            data = connection.recv(16)
            print('received {!r}'.format(data))
            if data:
                print('sending data back to the client')
                connection.sendall(data)
            else:
                print('no data from', client_address)
                break

    finally:
        # Clean up the connection
        print("Closing current connection")
        connection.close()

Starting up on 192.168.0.103 port 65452
waiting for a connection


KeyboardInterrupt: 

## Test server

In [1]:

from context import rmlib
#Imports 
from time import sleep
import numpy as np
import rmlib
from rmlib.rmtools.asm_BT_lib.asm_tree_Basic import augment_RM
import rmlib.rmtools as rm
from config import robotConfig

robot = rmlib.robot.Robot( robotConfig )

augment_RM( robot )


Loaded: /home/nvidia/dev_rmstudio/rmlib/rmlib/rmtools Exists?: True
Loaded: /home/nvidia/dev_rmstudio/rmlib Exists?: True
Setting up robot please wait...
my_components: {'arm_config': {'ip_address': '192.168.0.101', 'default_joint_accel': 0.8, 'default_linear_speed': 0.1, 'default_joint_speed': 0.7, 'module_name': 'arms.ur5', 'max_linear_accel': 1.2, 'class_name': 'UR5', 'max_joint_speed': 1.05, 'max_linear_speed': 0.25, 'xmlrpc_port': '8003', 'default_linear_accel': 0.8, 'max_joint_accel': 1.4}, 'cam_config': {'pc_cam_offset': [-0.037, -0.033, -0.079], 'module_name': 'cameras.realsense', 'ci_cam_offset': [-0.036, -0.028, -0.079], 'camera_model': 'd410', 'class_name': 'RealSense'}, 'hand_config': {'finger_length': 0.0415, 'finger_depth': 0.014, 'module_name': 'hands.smarthand', 'class_name': 'SmartHand', 'finger_width_outer': 0.015, 'finger_width_inner': 0.0}, 'ft_config': {'max_workers': 10, 'ip_address': '192.168.0.100', 'filter': {'alpha': 0.012, 'beta': 0.035}, 'local_port': 20000,

In [2]:
import socket
import numpy as np
import struct
HOST = '192.168.0.103'
PORT= 65458

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#sock.connect((HOST, PORT))
    
# Bind the socket to the port
server_address = (HOST, PORT)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(server_address)
print('Starting up on {} port {}'.format(*server_address))

# Listen for incoming connections
sock.listen(1)

try:
    while True:
        # Wait for a connection
        print('waiting for a connection')
        connection, client_address = sock.accept()
        try:
            print('connection from', client_address)

            # Receive the data in small chunks and retransmit it
            while True:
                command = connection.recv(16)
                print('received {!r}'.format(command))
                if command==b'end':
                    break
                if command:
                    print('sending data back to the client')
                    data=np.array([[-0.99934441,-0.00610222  ,0.03568637 ,-0.14532579],
                                           [-0.00426994  ,0.99867947  ,0.05119661 ,-0.30391228],
                                           [-0.03595166  ,0.05101066 ,-0.9980508  , 0.26136942],
                                           [ 0.          ,0.          ,0.          ,1.        ]])

                    print(data)
                            #dat=bytes(data[i][j])#.encode('ascii')  arr.tolist()
                    posedatabyte=struct.pack('ffffffffffffffff',
                                data[0][0],data[0][1],data[0][2],data[0][3],
                                data[1][0],data[1][1],data[1][2],data[1][3],
                                data[2][0],data[2][1],data[2][2],data[2][3],
                                data[3][0],data[3][1],data[3][2],data[3][3])
                    connection.send(posedatabyte)      
                else:
                    print('no data from', client_address)
                    break
                    
            if command==b'end':
                break 
        finally:
            # Clean up the connection
            print("Closing current connection")
            connection.close()
                   
finally:
        # Clean up the connection
        print("Closing+shutting down current connection")
        #connection.shutdown(sock.SHUT_RDWR) 
        connection.close()        

Starting up on 192.168.0.103 port 65458
waiting for a connection
connection from ('192.168.0.102', 46788)
received b'u'
sending data back to the client
[[-0.99934441 -0.00610222  0.03568637 -0.14532579]
 [-0.00426994  0.99867947  0.05119661 -0.30391228]
 [-0.03595166  0.05101066 -0.9980508   0.26136942]
 [ 0.          0.          0.          1.        ]]
received b'h'
sending data back to the client
[[-0.99934441 -0.00610222  0.03568637 -0.14532579]
 [-0.00426994  0.99867947  0.05119661 -0.30391228]
 [-0.03595166  0.05101066 -0.9980508   0.26136942]
 [ 0.          0.          0.          1.        ]]
received b'end'
Closing current connection
Closing+shutting down current connection


In [4]:
x=0
f=5
try:
    f> 3
except:
    print(Exception("Something went wrong") )
    print("testo")
    


finally:
    print("blah")

blah
