In [5]:
import socket
import numpy as np
import struct

#HOST = '127.0.0.1'  # Standard loopback interface address (localhost)
HOST = '192.168.0.103'

#192.168.0.103
PORT = 65453       # Port to listen on (non-privileged ports are > 1023)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    
    #s.settimeout(0.1)
    conn, addr = s.accept()
    with conn:
        print('Connected by', addr)
        s.setblocking(False)
        inputstring=0
        while True:
            #while inputstring!='end':
                inputstring=input("") #Press Enter to continue...
                if (inputstring=='h' or inputstring=='j' or inputstring=='k' or inputstring=='l' or 
                    inputstring=='u' or inputstring=='o'or inputstring=='y' or inputstring=='i' or 
                    inputstring=='z' or inputstring=='x' or inputstring=='d' or inputstring=='c'or
                    inputstring=='home'):
                    
                    data=inputstring.encode('ascii')    
                    print(data)
                    conn.send(data)
                  
                if inputstring=='g': 
                    data=np.array([[-0.99934441,-0.00610222  ,0.03568637 ,-0.14532579],
                                   [-0.00426994  ,0.99867947  ,0.05119661 ,-0.30391228],
                                   [-0.03595166  ,0.05101066 ,-0.9980508  , 0.26136942],
                                   [ 0.          ,0.          ,0.          ,1.        ]])

                    print(data)
                            #dat=bytes(data[i][j])#.encode('ascii')  arr.tolist()
                    dat=struct.pack('ffffffffffffffff',
                                data[0][0],data[0][1],data[0][2],data[0][3],
                                data[1][0],data[1][1],data[1][2],data[1][3],
                                data[2][0],data[2][1],data[2][2],data[2][3],
                                data[3][0],data[3][1],data[3][2],data[3][3])
                    conn.send(dat)
                
                    
                if inputstring=='end': 
                    data=b'end'
                    print(data)
                    conn.send(data) 
                    break
                #data = conn.recv(1024)
                
                #if not data:
                   # break
                

Connected by ('192.168.0.102', 37510)


 g


[[-0.99934441 -0.00610222  0.03568637 -0.14532579]
 [-0.00426994  0.99867947  0.05119661 -0.30391228]
 [-0.03595166  0.05101066 -0.9980508   0.26136942]
 [ 0.          0.          0.          1.        ]]


 end


b'end'


In [2]:
data=np.array([[-0.99934441,-0.00610222  ,0.03568637 ,-0.14532579],
                                   [-0.00426994  ,0.99867947  ,0.05119661 ,-0.30391228],
                                   [-0.03595166  ,0.05101066 ,-0.9980508  , 0.26136942],
                                   [ 0.          ,0.          ,0.          ,1.        ]])

print(data[i][:])
print(data[i][:].tolist())

[-0.99934441 -0.00610222  0.03568637 -0.14532579]
[-0.99934441, -0.00610222, 0.03568637, -0.14532579]


In [7]:
import numpy as np

a=np.array([[-0.99934441,-0.00610222  ,0.03568637 ,-0.14532579],
 [-0.00426994  ,0.99867947  ,0.05119661 ,-0.30391228],
 [-0.03595166  ,0.05101066 ,-0.9980508  , 0.26136942],
 [ 0.          ,0.          ,0.          ,1.        ]])

for i in range(4):
    for j in range(4):   
        dat=data[i][j]
        print(dat)

-0.99934441
-0.00610222
0.03568637
-0.14532579
-0.00426994
0.99867947
0.05119661
-0.30391228
-0.03595166
0.05101066
-0.9980508
0.26136942
0.0
0.0
0.0
1.0


In [17]:
print(a[0:3,0:3])

[[-0.99934441 -0.00610222  0.03568637]
 [-0.00426994  0.99867947  0.05119661]
 [-0.03595166  0.05101066 -0.9980508 ]]


SyntaxError: invalid syntax (<ipython-input-11-fccbde121c31>, line 1)

In [7]:
import struct
  
# '?' -> _BOOL , 'h' -> short, 'i' -> int and 'l' -> long
var = struct.pack('?hil', True, 2, 5, 445)
print(var)
  
# struct.unpack() return a tuples
# Variables V1, V2, V3,.. are returned as elements of tuple
tup = struct.unpack('?hil', var)
print(tup)
  
# q -> long long int and f -> float
var = struct.pack('qf', 5, 2.3)
print(var)
tup = struct.unpack('qf', var)
print(tup)

b'\x01\x00\x02\x00\x05\x00\x00\x00\xbd\x01\x00\x00\x00\x00\x00\x00'
(True, 2, 5, 445)
b'\x05\x00\x00\x00\x00\x00\x00\x0033\x13@'
(5, 2.299999952316284)
