In [5]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
#  array([[ 1,  2,  3,  4],
#         [ 5,  6,  7,  8],
#         [ 9, 10, 11, 12]])
arr = np.delete(arr, 0, 1)
print(arr)
newcol=np.array([[13],[14],[15]])
arr =np.concatenate((arr, newcol), 1)
print("after concat")
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
after concat
[[ 2  3  4 13]
 [ 6  7  8 14]
 [10 11 12 15]]


In [9]:
xforce_normalized=1
yforce_normalized=2
zforce_normalized=3
rolltorque_normalized=4
pitchtorque_normalized=5


FT_list_x_normalized=[]
FT_list_y_normalized=[]
FT_list_z_normalized=[]
FT_list_roll_normalized=[]
FT_list_pitch_normalized=[]

In [15]:
arr2= np.array([[],[],[],[],[]])
print(arr2.shape)

newcol=np.array([[xforce_normalized],[yforce_normalized],[zforce_normalized],[rolltorque_normalized],[pitchtorque_normalized]])


newcol2=np.array([[9],[9],[9],[9],[9]])
newcol3=np.array([[8],[8],[8],[8],[8]])
arr2 =np.concatenate((arr2, newcol), 1)
arr2 =np.concatenate((arr2, newcol2), 1)
arr2 =np.concatenate((arr2, newcol3), 1)
print("after concat")
print(arr2)
arr3 = np.delete(arr2, 0, 1)

print(arr3)
print(arr3.shape)

(5, 0)
after concat
[[1. 9. 8.]
 [2. 9. 8.]
 [3. 9. 8.]
 [4. 9. 8.]
 [5. 9. 8.]]
[[9. 8.]
 [9. 8.]
 [9. 8.]
 [9. 8.]
 [9. 8.]]
(5, 2)


In [16]:
print(arr3.shape)
print(arr3.shape[1])

(5, 2)
2
