In [23]:
import numpy as np
from scipy.spatial.transform import Rotation as R
TransRotatmatrix=np.array([
[-0.99937006,-0.00793447 ,0.03459093, -0.23718183],
[-0.00750209 , 0.99989233  ,0.01261162 ,-0.59998911],
[-0.03468727  ,0.01234417 ,-0.99932198 , 0.0638135 ],
[ 0.         , 0.       ,   0.      ,    1.        ]])

def rot2rpy(Rt, degrees=False):
    """ Converts a rotation matrix into rpy / intrinsic xyz euler angle form.
    Args:    Rt (ndarray): The rotation matrix.
    Returns: ndarray: Angles in rpy / intrinsic xyz euler angle form.
    """
    return R.from_matrix(Rt).as_euler('xyz', degrees=degrees)


def rpy2rot(rpy, degrees=False):
    """Converts rpy / intrinsic xyz euler angles into a rotation matrix.
    Args:    rpy (array-like): rpy / intrinsic xyz euler angles.
             degrees (bool) : Whether or not euler_angles are in degrees (True), or radians (False).
    Returns: ndarray: The rotation matrix.
    """
    return R.from_euler('xyz', rpy, degrees=degrees).as_matrix()

#TransRotatmatrix=robot.arm.get_tcp_pose() 
print(TransRotatmatrix)
x_pose=TransRotatmatrix[0][3]*39.3701  #convert to inches 
y_pose=TransRotatmatrix[1][3]*39.3701
z_pose=TransRotatmatrix[2][3]*39.3701
print("")
print(TransRotatmatrix[0:3][0:3])
print("hello")
rpy=rot2rpy(TransRotatmatrix[0:3,0:3],True)
roll=rpy[0]  #In degrees!
pitch=rpy[1]
yaw=rpy[2]
print(x_pose,y_pose,z_pose)
print(roll,pitch,yaw)

rpy=[180, 0, -180]
mat=rpy2rot(rpy)

print("output")
print(mat)





[[-0.99937006 -0.00793447  0.03459093 -0.23718183]
 [-0.00750209  0.99989233  0.01261162 -0.59998911]
 [-0.03468727  0.01234417 -0.99932198  0.0638135 ]
 [ 0.          0.          0.          1.        ]]

[[-0.99937006 -0.00793447  0.03459093 -0.23718183]
 [-0.00750209  0.99989233  0.01261162 -0.59998911]
 [-0.03468727  0.01234417 -0.99932198  0.0638135 ]]
hello
-9.337872365283001 -23.621631259611 2.5123438763499997
179.29228725251474 1.9878329916962305 -179.56989892877252
output
[[-0.59846007 -0.47945786  0.64184555]
 [-0.80115264  0.35815445 -0.47945786]
 [ 0.         -0.80115264 -0.59846007]]


In [30]:
rpy=[180, 0, -180]
mat=rpy2rot(rpy,True)

print("output")
print(mat)


output
[[-1.00000000e+00 -1.22464680e-16 -1.49975978e-32]
 [-1.22464680e-16  1.00000000e+00  1.22464680e-16]
 [ 0.00000000e+00  1.22464680e-16 -1.00000000e+00]]


In [29]:
BlockInsertPoseV2=np.array(
[[-0.59846007, -0.47945786 , 0.64184555,-0.23718183],
 [-0.80115264 , 0.35815445, -0.47945786,-0.59998911],
 [ 0.        , -0.80115264 ,-0.59846007, 0.0638135 ],
 [ 0.         , 0.       ,   0.      ,    1.        ]])

rpy2=rot2rpy(BlockInsertPoseV2[0:3,0:3],True)
rpy=rot2rpy(mat,True)
print(rpy2)

[-1.26759687e+02  3.13864642e-08 -1.26759687e+02]


In [34]:
BlockInsertPoseV2=np.array(
[[-1 ,0,0,                   -0.23718183],
 [-1.22464680e-16 ,  1,  0,                 -0.59998911],
 [ 0 , 0, -1,                 0.0638135],
 [ 0.   , 0.  ,   0.      ,    1.        ]])
rpy2=rot2rpy(BlockInsertPoseV2[0:3,0:3],True)
rpy=rot2rpy(mat,True)
print(rpy2)

[ 180.    0. -180.]
