In [ ]:
%run -i '2WayComms_and_RC-V2_dummypolicy.py'

## test client

In [1]:
import socket
import numpy as np

from time import sleep
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F
import torch.optim as optim

HOST_SnS = '128.138.224.89' #192.168.0.103'#
PORT_SnS= 65492
# Create a TCP/IP socket
sock_SnS = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
server_address_SnS = (HOST_SnS, PORT_SnS)
print('connecting to {} port {}'.format(*server_address_SnS))
sock_SnS.connect(server_address_SnS)

import twoWayComms_and_RC_V8_GRU_successfail

class GRUNet(nn.Module):
        def __init__(self, input_dim, hidden_dim, output_dim, n_layers, drop_prob=0.2):
            super(GRUNet, self).__init__()
            self.hidden_dim = hidden_dim
            self.n_layers = n_layers

            self.gru = nn.GRU(input_dim, hidden_dim, n_layers, batch_first=True, dropout=drop_prob)
            self.fc = nn.Linear(hidden_dim, output_dim)
            self.relu = nn.ReLU()

        def forward(self, x, h):
            out, h = self.gru(x, h)
            out = self.fc(self.relu(out[:,-1]))
            return out, h

        def init_hidden(self, batch_size):
            weight = next(self.parameters()).data
            hidden = weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device)
            return hidden

device = torch.device("cpu")
try:
     #while True:
        """Restart
        data = sock.recv(16)
            #amount_received += len(data)
        print('received {!r}'.format(data))
        """

        data = sock_SnS.recv(64)  #48 bytes
        #print(data)
        #value = struct.unpack('f',data)
        #unpacked = struct.unpack('f', data)
        print('received {!r}'.format(data))
        if data==b'start':
            
            print("starting rl policy")
#             %run -i 'twoWayComms_and_RC_V8_GRU_successfail.py'
            twoWayComms_and_RC_V8_GRU_successfail.execute_rl()
   
            endmsg='end'
            data1=endmsg.encode('ascii')    
            sock_SnS.sendall(data1)
        #if (inputstring==b'end'):
        #   break    
        """"""
finally:       
    print('Error. closing SnS socket')
    sock_SnS.close()


connecting to 128.138.224.89 port 65492
blue robot is being used. Please change the bot variable if this is incorrect
port= /dev/ttyACM0
connecting to 128.138.224.89 port 65482
server_address ('128.138.224.89', 65482)
connected
received b'start'
starting rl policy
GRU model loaded


 u


inputstring= u
data sent u


 obs


inputstring= obs
data sent obs
currentpose: x -3.716489767052978 y -12.861036079916358 z 14.515429594936966
roll 179.719888052832 pitch 1.1093841814566383 yaw 179.16846427107325
forcetorque: [-2.250107526779175, -0.27394700050354004, -1.1767767667770386, -0.045378994196653366, 0.022316694259643555, 0.012499657459557056]
normalized5channel:
[[0.47698621]
 [0.43048717]
 [0.92188168]
 [0.58823637]
 [0.54184902]]
normalized5channel.shape:  (5, 1)
data array for GRU not filled. Currently at size of  1
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.716002252421528 y -12.860955120807887 z 14.51526650339961
roll 179.71874097768656 pitch 1.1078249832727454 yaw 179.16980226230456
forcetorque: [-2.3192176818847656, -0.24370546638965607, -1.2164193391799927, -0.04300228878855705, 0.021384699270129204, 0.011788868345320225]
normalized5channel:
[[0.47698621 0.47540619]
 [0.43048717 0.43084315]
 [0.92188168 0.92161072]
 [0.58823637 0.58839298]
 [0.54184902 0.54176589]]
normalized5channel.shape:  (5, 2)
data array for GRU not filled. Currently at size of  2
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.716061211772263 y -12.860851868611574 z 14.515144478076696
roll 179.71897403581357 pitch 1.1113273772727272 yaw 179.16849688250394
forcetorque: [-2.2930421829223633, -0.23863665759563446, -1.3246608972549438, -0.041942089796066284, 0.02421114221215248, 0.009355831891298294]
normalized5channel:
[[0.47698621 0.47540619 0.47600462]
 [0.43048717 0.43084315 0.43090282]
 [0.92188168 0.92161072 0.92087086]
 [0.58823637 0.58839298 0.58846284]
 [0.54184902 0.54176589 0.542018  ]]
normalized5channel.shape:  (5, 3)
data array for GRU not filled. Currently at size of  3
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.715880227098614 y -12.861178051686288 z 14.515258290156723
roll 179.71990126366882 pitch 1.1093851236453156 yaw 179.170491094434
forcetorque: [-2.184835433959961, -0.31098464131355286, -1.2791767120361328, -0.04048052802681923, 0.02338472753763199, 0.010995338670909405]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849]
 [0.43048717 0.43084315 0.43090282 0.43005118]
 [0.92188168 0.92161072 0.92087086 0.92118176]
 [0.58823637 0.58839298 0.58846284 0.58855915]
 [0.54184902 0.54176589 0.542018   0.54194428]]
normalized5channel.shape:  (5, 4)
data array for GRU not filled. Currently at size of  4
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.7157274021148683 y -12.861163971841336 z 14.515577433308959
roll 179.7205521107394 pitch 1.109465861215232 yaw 179.17121025703563
forcetorque: [-2.331338882446289, -0.21616066992282867, -1.252490520477295, -0.041415080428123474, 0.02589499019086361, 0.010814155451953411]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849 0.47512907]
 [0.43048717 0.43084315 0.43090282 0.43005118 0.4311674 ]
 [0.92188168 0.92161072 0.92087086 0.92118176 0.92136416]
 [0.58823637 0.58839298 0.58846284 0.58855915 0.58849757]
 [0.54184902 0.54176589 0.542018   0.54194428 0.54216818]]
normalized5channel.shape:  (5, 5)
data array for GRU not filled. Currently at size of  5
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.715815107815713 y -12.860822535601258 z 14.515077598813177
roll 179.719397291695 pitch 1.1085992509536413 yaw 179.1711894636191
forcetorque: [-2.2827765941619873, -0.29659128189086914, -1.2551426887512207, -0.040012259036302567, 0.02470516785979271, 0.013095623813569546]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849 0.47512907 0.47623932]
 [0.43048717 0.43084315 0.43090282 0.43005118 0.4311674  0.43022061]
 [0.92188168 0.92161072 0.92087086 0.92118176 0.92136416 0.92134603]
 [0.58823637 0.58839298 0.58846284 0.58855915 0.58849757 0.58859001]
 [0.54184902 0.54176589 0.542018   0.54194428 0.54216818 0.54206206]]
normalized5channel.shape:  (5, 6)
data array for GRU not filled. Currently at size of  6
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.7157608417466284 y -12.860976240575313 z 14.515437808179856
roll 179.72172401039052 pitch 1.1116830648662377 yaw 179.1705334006165
forcetorque: [-2.436375856399536, -0.36668381094932556, -1.0869932174682617, -0.04632885009050369, 0.025070780888199806, 0.010533766821026802]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849 0.47512907 0.47623932
  0.47272767]
 [0.43048717 0.43084315 0.43090282 0.43005118 0.4311674  0.43022061
  0.42939552]
 [0.92188168 0.92161072 0.92087086 0.92118176 0.92136416 0.92134603
  0.92249537]
 [0.58823637 0.58839298 0.58846284 0.58855915 0.58849757 0.58859001
  0.58817378]
 [0.54184902 0.54176589 0.542018   0.54194428 0.54216818 0.54206206
  0.54209467]]
normalized5channel.shape:  (5, 7)
data array for GRU not filled. Currently at size of  7
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.715679002647847 y -12.861171011763812 z 14.515455407986044
roll 179.7211954859431 pitch 1.1102389982604002 yaw 179.17123115482542
forcetorque: [-2.283703565597534, -0.32696688175201416, -1.3931406736373901, -0.045315105468034744, 0.019527753815054893, 0.008267803117632866]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849 0.47512907 0.47623932
  0.47272767 0.47621813]
 [0.43048717 0.43084315 0.43090282 0.43005118 0.4311674  0.43022061
  0.42939552 0.42986305]
 [0.92188168 0.92161072 0.92087086 0.92118176 0.92136416 0.92134603
  0.92249537 0.92040279]
 [0.58823637 0.58839298 0.58846284 0.58855915 0.58849757 0.58859001
  0.58817378 0.58824058]
 [0.54184902 0.54176589 0.542018   0.54194428 0.54216818 0.54206206
  0.54209467 0.54160027]]
normalized5channel.shape:  (5, 8)
data array for GRU not filled. Currently at size of  8
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.715781668183953 y -12.861215597939491 z 14.515308742934465
roll 179.72042952983523 pitch 1.1108312268891918 yaw 179.17050343570918
forcetorque: [-1.9458290338516235, -0.2716237008571625, -1.2672643661499023, -0.04512893408536911, 0.0166690144687891, 0.013164044357836246]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849 0.47512907 0.47623932
  0.47272767 0.47621813 0.48394275]
 [0.43048717 0.43084315 0.43090282 0.43005118 0.4311674  0.43022061
  0.42939552 0.42986305 0.43051452]
 [0.92188168 0.92161072 0.92087086 0.92118176 0.92136416 0.92134603
  0.92249537 0.92040279 0.92126318]
 [0.58823637 0.58839298 0.58846284 0.58855915 0.58849757 0.58859001
  0.58817378 0.58824058 0.58825285]
 [0.54184902 0.54176589 0.542018   0.54194428 0.54216818 0.54206206
  0.54209467 0.54160027 0.54134528]]
normalized5channel.shape:  (5, 9)
data array for GRU not filled. Currently at size of  9
BUTTON NOT PRESSED


 obs


inputstring= obs
data sent obs
currentpose: x -3.7160708916656673 y -12.86076973618269 z 14.51492741380036
roll 179.71838927802858 pitch 1.1112604870848786 yaw 179.17187229667604
forcetorque: [-2.361196994781494, -0.3140656352043152, -0.6989880204200745, -0.0396343432366848, 0.0212135948240757, 0.014191762544214725]
normalized5channel:
[[0.47698621 0.47540619 0.47600462 0.47847849 0.47512907 0.47623932
  0.47272767 0.47621813 0.48394275 0.47444644]
 [0.43048717 0.43084315 0.43090282 0.43005118 0.4311674  0.43022061
  0.42939552 0.42986305 0.43051452 0.43001491]
 [0.92188168 0.92161072 0.92087086 0.92118176 0.92136416 0.92134603
  0.92249537 0.92040279 0.92126318 0.92514747]
 [0.58823637 0.58839298 0.58846284 0.58855915 0.58849757 0.58859001
  0.58817378 0.58824058 0.58825285 0.58861491]
 [0.54184902 0.54176589 0.542018   0.54194428 0.54216818 0.54206206
  0.54209467 0.54160027 0.54134528 0.54175063]]
normalized5channel.shape:  (5, 10)
GRU Output 0.013813227415084839
BUTTON NOT PRESSED


KeyboardInterrupt: Interrupted by user

In [53]:
a=[0.2, -0.1, 0.1, 0.013, 0.001, -0.007]
b=[0.2, 0.0, 0.5, 0.033, 0.006, -0.008]
c=[0.1, 0.1, 1.3, 0.013, -0.002, -0.007]
d=[0.1, 0.1, 1.2, 0.017, -0.001, -0.008]
e=[0.0, 0.1, 0.4, 0.026, -0.001, -0.00899]

LL=[]
LL.append(a)
LL.append(b)
LL.append(c)
L2=[0]*6
print("LL len",len(LL))
for i in range(len(a)): 
    #print("i:",i)
    L2[i]=0
    for j in range(len(LL)):  
        L2[i]+=LL[j][i]    
    L2[i]=L2[i]/(len(LL))


LL len 3
[0.16666666666666666, 0.0, 0.6333333333333333, 0.019666666666666666, 0.0016666666666666668, -0.007333333333333333]
