In [18]:
import socket
import struct
from scipy.spatial.transform import Rotation as R
import numpy as np
#HOST = '127.0.0.1'  # The server's hostname or IP address
HOST = '192.168.0.103'
PORT = 65453      # The port used by the server

def rot2rpy(Rt, degrees=False):
    """ Converts a rotation matrix into rpy / intrinsic xyz euler angle form.
    Args:    Rt (ndarray): The rotation matrix.
    Returns: ndarray: Angles in rpy / intrinsic xyz euler angle form.
    """
    return R.from_matrix(Rt).as_euler('xyz', degrees=degrees)


def rpy2rot(rpy, degrees=False):
    """Converts rpy / intrinsic xyz euler angles into a rotation matrix.
    Args:    rpy (array-like): rpy / intrinsic xyz euler angles.
             degrees (bool) : Whether or not euler_angles are in degrees (True), or radians (False).
    Returns: ndarray: The rotation matrix.
    """
    return R.from_euler('xyz', rpy, degrees=degrees).as_matrix()


with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    #s.sendall(message)
    while True:
        data = s.recv(64)  #48 bytes
        #print(data)
        if data==b'end':
            break
        #value = struct.unpack('f',data)
        unpacked = struct.unpack('ffffffffffffffff', data)
        #print(unpacked)
        #print('Received', repr(data))
        TransRotatmatrix=np.zeros([4,4])
        for i in range(4):
            TransRotatmatrix[i][:]=unpacked[0+(4*i):4+(4*i)]
        print(TransRotatmatrix)
        rpy=rot2rpy(TransRotatmatrix[0:3,0:3],True)
        x=TransRotatmatrix[0][3]
        y=TransRotatmatrix[1][3]
        z=TransRotatmatrix[2][3]
        roll=rpy[0]  #In degrees!
        pitch=rpy[1]
        yaw=rpy[2]
        print("x",x,"y",y,"z",z)
        print("roll",roll,"pitch",pitch,"yaw",yaw)

[[-0.99934441 -0.00610222  0.03568637 -0.14532579]
 [-0.00426994  0.99867946  0.05119661 -0.30391228]
 [-0.03595166  0.05101066 -0.99805081  0.26136941]
 [ 0.          0.          0.          1.        ]]
x -0.14532579481601715 y -0.30391228199005127 z 0.26136940717697144
roll 177.07414215504588 pitch 2.060322291013616 yaw -179.75519145125745
