In [7]:
import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
from numpy import genfromtxt

import open3d as o3d
%matplotlib notebook

data = genfromtxt('largestCloud.csv', delimiter=',')

In [8]:
print(data)

[[-0.15600199 -0.23572526  0.00878815]
 [-0.15240096 -0.23814208  0.0075276 ]
 [-0.13455915 -0.23609526  0.0051014 ]
 ...
 [-0.16273912 -0.49623942  0.00432637]
 [ 0.05986541 -0.53210573 -0.00286444]
 [ 0.05790634 -0.35795721 -0.00235283]]


In [12]:

#fig = plt.figure()
#ax = plt.axes(projection='3d')
#ax.plot3D(data[:,0], data[:,1], data[:,2], 'gray')
#ax.scatter3D(data[:,0], data[:,1], data[:,2], cmap='Greens')
#ax.scatter(data[:,0], data[:,1], data[:,2], marker='.')

pcd = o3d.io.read_point_cloud(data)
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd], zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

#http://www.open3d.org/docs/release/tutorial/Basic/pointcloud.html

TypeError: read_point_cloud(): incompatible function arguments. The following argument types are supported:
    1. (filename: unicode, format: unicode = u'auto', remove_nan_points: bool = True, remove_infinite_points: bool = True, print_progress: bool = False) -> open3d.open3d.geometry.PointCloud

Invoked with: array([[-0.15600199, -0.23572526,  0.00878815],
       [-0.15240096, -0.23814208,  0.0075276 ],
       [-0.13455915, -0.23609526,  0.0051014 ],
       ...,
       [-0.16273912, -0.49623942,  0.00432637],
       [ 0.05986541, -0.53210573, -0.00286444],
       [ 0.05790634, -0.35795721, -0.00235283]])